export const albums = [
  {
    id: "ghostly-field-club",
    catalog: "ZCDS-0001",
    year: "2003",
    color: "rgba(86, 214, 189, 0.18)",
    source: "https://thwiki.cc/%E8%93%AE%E5%8F%B0%E9%87%8E%E5%A4%9C%E8%A1%8C/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "莲台野夜行",
      ja: "蓮台野夜行",
    },
    summary: {
      zh: "梅莉与莲子夜访冥界边界的开端。铁路、墓地与结界感交错，是秘封叙事最经典的入口。",
      ja: "メリーと蓮子が冥界の境界をめぐる夜。鉄道、墓地、結界の感覚が交差する秘封物語の入口です。",
    },
    tracks: [
      track("夜のデンデラ野を逝く", "assets/audio/ghostly-field-club/01.mp3"),
      track("少女秘封倶楽部", "assets/audio/ghostly-field-club/02.mp3"),
      track("東方妖々夢　～ Ancient Temple", "assets/audio/ghostly-field-club/03.mp3"),
      track("古の冥界寺", "assets/audio/ghostly-field-club/04.mp3"),
      track("幻視の夜　～ Ghostly Eyes", "assets/audio/ghostly-field-club/05.mp3"),
      track("魔術師メリー", "assets/audio/ghostly-field-club/06.mp3"),
      track("月の妖鳥、化猫の幻", "assets/audio/ghostly-field-club/07.mp3"),
      track("過去の花　～ Fairy of Flower", "assets/audio/ghostly-field-club/08.mp3"),
      track("魔法少女十字軍", "assets/audio/ghostly-field-club/09.mp3"),
      track("少女幻葬　～ Necro-Fantasy", "assets/audio/ghostly-field-club/10.mp3"),
      track("幻想の永遠祭", "assets/audio/ghostly-field-club/11.mp3"),
    ],
    story: storyPlaceholders([
      ["夜行计划", "夜の計画"],
      ["秘封俱乐部", "秘封倶楽部"],
      ["古寺与边界", "古寺と境界"],
      ["梅莉的视野", "メリーの視界"],
      ["月夜的异常", "月夜の異変"],
      ["归途", "帰り道"],
    ]),
  },
  {
    id: "changeability-of-strange-dream",
    catalog: "ZCDS-0002",
    year: "2004",
    color: "rgba(77, 116, 176, 0.24)",
    source: "https://thwiki.cc/%E6%A2%A6%E8%BF%9D%E7%A7%91%E5%AD%A6%E4%B8%96%E7%BA%AA/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "梦违科学世纪",
      ja: "夢違科学世紀",
    },
    summary: {
      zh: "梦境、科学与虚实错位的记录。梅莉所见的幻想与莲子的理性推导在这里形成张力。",
      ja: "夢、科学、現実のずれをめぐる記録。メリーの見る幻想と蓮子の理性的な推論が緊張を生みます。",
    },
    tracks: [
      track("童祭　～ Innocent Treasures", "assets/audio/changeability-of-strange-dream/01.mp3"),
      track("華胥の夢", "assets/audio/changeability-of-strange-dream/02.mp3"),
      track("上海紅茶館　～ Chinese Tea", "assets/audio/changeability-of-strange-dream/03.mp3"),
      track("ヴォヤージュ1969", "assets/audio/changeability-of-strange-dream/04.mp3"),
      track("科学世紀の少年少女", "assets/audio/changeability-of-strange-dream/05.mp3"),
      track("永夜の報い　～ Imperishable Night", "assets/audio/changeability-of-strange-dream/06.mp3"),
      track("夜が降りてくる　～ Evening Star", "assets/audio/changeability-of-strange-dream/07.mp3"),
      track("人形裁判　～ 人の形弄びし少女", "assets/audio/changeability-of-strange-dream/08.mp3"),
      track("夢と現の境界", "assets/audio/changeability-of-strange-dream/09.mp3"),
      track("幻想機械　～ Phantom Factory", "assets/audio/changeability-of-strange-dream/10.mp3"),
      track("幽玄の槭樹　～ Eternal Dream", "assets/audio/changeability-of-strange-dream/11.mp3"),
    ],
    story: storyPlaceholders([
      ["梦的入口", "夢の入口"],
      ["科学世纪", "科学世紀"],
      ["坐标与推理", "座標と推理"],
      ["梦与现的境界", "夢と現の境界"],
      ["记录者", "記録者"],
    ]),
  },
  {
    id: "retrospective-53-minutes",
    catalog: "ZCDS-0003",
    year: "2006",
    color: "rgba(215, 179, 99, 0.2)",
    source: "https://thwiki.cc/%E5%8D%AF%E9%85%89%E4%B8%9C%E6%B5%B7%E9%81%93/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "卯酉东海道",
      ja: "卯酉東海道",
    },
    summary: {
      zh: "两人乘坐新干线穿过东京与京都之间的现实地理，幻想则从车窗和时间表的缝隙渗出。",
      ja: "東京と京都を結ぶ新幹線の旅。現実の地理を進みながら、幻想が車窓と時刻表の隙間から滲みます。",
    },
    tracks: [
      track("ヒロシゲ36号　～ Neo Super-Express", "assets/audio/retrospective-53-minutes/01.mp3"),
      track("53ミニッツの青い海", "assets/audio/retrospective-53-minutes/02.mp3"),
      track("竹取飛翔　～ Lunatic Princess", "assets/audio/retrospective-53-minutes/03.mp3"),
      track("彼岸帰航　～ Riverside View", "assets/audio/retrospective-53-minutes/04.mp3"),
      track("青木ヶ原の伝説", "assets/audio/retrospective-53-minutes/05.mp3"),
      track("お宇佐さまの素い幡", "assets/audio/retrospective-53-minutes/06.mp3"),
      track("月まで届け、不死の煙", "assets/audio/retrospective-53-minutes/07.mp3"),
      track("レトロスペクティブ京都", "assets/audio/retrospective-53-minutes/08.mp3"),
      track("ラクトガール　～ 少女密室", "assets/audio/retrospective-53-minutes/09.mp3"),
      track("千年幻想郷　～ History of the Moon", "assets/audio/retrospective-53-minutes/10.mp3"),
      track("最も澄みわたる空と海", "assets/audio/retrospective-53-minutes/11.mp3"),
    ],
    story: storyPlaceholders([
      ["五十三分钟", "五十三分"],
      ["车窗外的海", "車窓の海"],
      ["旅行中的传说", "旅の伝説"],
      ["京都回望", "京都を振り返る"],
      ["最澄澈的天空与海", "澄みわたる空と海"],
    ]),
  },
  {
    id: "magical-astronomy",
    catalog: "ZCDS-0004",
    year: "2006",
    color: "rgba(113, 92, 171, 0.25)",
    source: "https://thwiki.cc/%E5%A4%A7%E7%A9%BA%E9%AD%94%E6%9C%AF/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "大空魔术",
      ja: "大空魔術",
    },
    summary: {
      zh: "天文、月面旅行和幻想边界共同展开。秘封组的视野从地上轨道延伸到大空之外。",
      ja: "天文、月面旅行、幻想の境界が重なります。秘封倶楽部の視線は地上の軌道から大空の彼方へ伸びます。",
    },
    tracks: [
      track("月面ツアーへようこそ", "assets/audio/magical-astronomy/01.mp3"),
      track("天空のグリニッジ", "assets/audio/magical-astronomy/02.mp3"),
      track("東の国の眠らない夜", "assets/audio/magical-astronomy/03.mp3"),
      track("車椅子の未来宇宙", "assets/audio/magical-astronomy/04.mp3"),
      track("Demystify Feast", "assets/audio/magical-astronomy/05.mp3"),
      track("衛星カフェテラス", "assets/audio/magical-astronomy/06.mp3"),
      track("G Free", "assets/audio/magical-astronomy/07.mp3"),
      track("大空魔術　～ Magical Astronomy", "assets/audio/magical-astronomy/08.mp3"),
      track("ネクロファンタジア", "assets/audio/magical-astronomy/09.mp3"),
      track("向こう側の月", "assets/audio/magical-astronomy/10.mp3"),
    ],
    story: storyPlaceholders([
      ["月面旅行", "月面ツアー"],
      ["格林尼治与卫星", "グリニッジと衛星"],
      ["未来宇宙", "未来宇宙"],
      ["重力之外", "重力の外"],
      ["对侧的月亮", "向こう側の月"],
    ]),
  },
  {
    id: "trojan-green-asteroid",
    catalog: "ZCDS-0012",
    year: "2012",
    color: "rgba(67, 150, 116, 0.24)",
    source: "https://thwiki.cc/%E9%B8%9F%E8%88%B9%E9%81%97%E8%BF%B9/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "鸟船遗迹",
      ja: "鳥船遺跡",
    },
    summary: {
      zh: "宇宙遗迹与绿色小行星的故事。科幻式的舞台让秘封叙事变得更加冷峻而辽远。",
      ja: "宇宙遺跡と緑の小惑星をめぐる物語。SF 的な舞台が秘封の物語をより冷たく遠いものにします。",
    },
    tracks: [
      track("衛星トリフネ", "assets/audio/trojan-green-asteroid/01.mp3"),
      track("トロヤ群の密林", "assets/audio/trojan-green-asteroid/02.mp3"),
      track("デザイアドライブ", "assets/audio/trojan-green-asteroid/03.mp3"),
      track("フェアリー冒険譚", "assets/audio/trojan-green-asteroid/04.mp3"),
      track("天鳥船神社", "assets/audio/trojan-green-asteroid/05.mp3"),
      track("夜空のユーフォーロマンス", "assets/audio/trojan-green-asteroid/06.mp3"),
      track("ハルトマンの妖怪少女", "assets/audio/trojan-green-asteroid/07.mp3"),
      track("天鳥船神社の結界", "assets/audio/trojan-green-asteroid/08.mp3"),
      track("感情の摩天楼　～ Cosmic Mind", "assets/audio/trojan-green-asteroid/09.mp3"),
      track("宇宙に浮かぶ幻想郷", "assets/audio/trojan-green-asteroid/10.mp3"),
    ],
    story: storyPlaceholders([
      ["卫星鸟船", "衛星トリフネ"],
      ["特洛伊群密林", "トロヤ群の密林"],
      ["天鸟船神社", "天鳥船神社"],
      ["结界观测", "結界観測"],
      ["宇宙中的幻想乡", "宇宙の幻想郷"],
    ]),
  },
  {
    id: "neo-traditionalism-of-japan",
    catalog: "ZCDS-0013",
    year: "2012",
    color: "rgba(186, 73, 90, 0.22)",
    source: "https://thwiki.cc/%E4%BC%8A%E5%A5%98%E8%AF%BA%E7%89%A9%E8%B4%A8/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "伊奘诺物质",
      ja: "伊弉諾物質",
    },
    summary: {
      zh: "旧日本、神话、科学与秘封组的观测互相纠缠，像一次从民俗学进入异界的实地调查。",
      ja: "古い日本、神話、科学、秘封倶楽部の観測が絡み合い、民俗学から異界へ入るフィールドワークのようです。",
    },
    tracks: [
      track("緑のサナトリウム", "assets/audio/neo-traditionalism-of-japan/01.mp3"),
      track("牛に引かれて善光寺参り", "assets/audio/neo-traditionalism-of-japan/02.mp3"),
      track("ハートフェルトファンシー", "assets/audio/neo-traditionalism-of-japan/03.mp3"),
      track("六十年目の東方裁判　～ Fate of Sixty Years", "assets/audio/neo-traditionalism-of-japan/04.mp3"),
      track("アガルタの風", "assets/audio/neo-traditionalism-of-japan/05.mp3"),
      track("イザナギオブジェクト", "assets/audio/neo-traditionalism-of-japan/06.mp3"),
      track("妖怪裏参道", "assets/audio/neo-traditionalism-of-japan/07.mp3"),
      track("アンノウンX　～ Unfound Adventure", "assets/audio/neo-traditionalism-of-japan/08.mp3"),
      track("日本中の不思議を集めて", "assets/audio/neo-traditionalism-of-japan/09.mp3"),
      track("素敵な墓場で暮しましょ", "assets/audio/neo-traditionalism-of-japan/10.mp3"),
    ],
    story: storyPlaceholders([
      ["疗养院与传说", "サナトリウムと伝説"],
      ["善光寺参拜", "善光寺参り"],
      ["阿加尔塔之风", "アガルタの風"],
      ["伊奘诺物质", "イザナギオブジェクト"],
      ["日本中的不可思议", "日本中の不思議"],
    ]),
  },
  {
    id: "dr-latencys-freak-report",
    catalog: "ZCDS-0016",
    year: "2016",
    color: "rgba(148, 132, 91, 0.25)",
    source: "https://thwiki.cc/%E7%87%95%E7%9F%B3%E5%8D%9A%E7%89%A9%E5%BF%97/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "燕石博物志",
      ja: "燕石博物誌",
    },
    summary: {
      zh: "都市传说、怪异报道与“Dr. Latency”的笔记。秘封组从观测者更进一步接近怪异的叙述中心。",
      ja: "都市伝説、怪異報告、Dr. Latency のノート。秘封倶楽部は観測者から怪異の中心へ近づいていきます。",
    },
    tracks: [
      track("他愛も無い二人の博物誌", "assets/audio/dr-latencys-freak-report/01.mp3"),
      track("凍り付いた永遠の都", "assets/audio/dr-latencys-freak-report/02.mp3"),
      track("Dr.レイテンシーの眠れなくなる瞳", "assets/audio/dr-latencys-freak-report/03.mp3"),
      track("九月のパンプキン", "assets/audio/dr-latencys-freak-report/04.mp3"),
      track("須臾はプランクを超えて", "assets/audio/dr-latencys-freak-report/05.mp3"),
      track("シュレディンガーの化猫", "assets/audio/dr-latencys-freak-report/06.mp3"),
      track("空中に沈む輝針城", "assets/audio/dr-latencys-freak-report/07.mp3"),
      track("禁忌の膜壁", "assets/audio/dr-latencys-freak-report/08.mp3"),
      track("故郷の星が映る海", "assets/audio/dr-latencys-freak-report/09.mp3"),
      track("ピュアヒューリーズ　～ 心の在処", "assets/audio/dr-latencys-freak-report/10.mp3"),
      track("永遠の三日天下", "assets/audio/dr-latencys-freak-report/11.mp3"),
    ],
    story: storyPlaceholders([
      ["博物志", "博物誌"],
      ["Dr. Latency", "Dr.レイテンシー"],
      ["短暂与普朗克", "須臾とプランク"],
      ["薛定谔的化猫", "シュレディンガーの化猫"],
      ["禁忌膜壁", "禁忌の膜壁"],
    ]),
  },
  {
    id: "dateless-bar-old-adam",
    catalog: "ZCDS-0017",
    year: "2016",
    color: "rgba(80, 80, 88, 0.33)",
    source: "https://thwiki.cc/%E6%97%A7%E7%BA%A6%E9%85%92%E9%A6%86/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "旧约酒馆",
      ja: "旧約酒場",
    },
    summary: {
      zh: "在酒馆里交换怪谈、谣言与观测结果。秘封叙事罕见地带着夜晚社交和都市阴影的气味。",
      ja: "酒場で怪談、噂、観測結果を交わす物語。夜の社交と都市の影を帯びた秘封です。",
    },
    tracks: [
      track("バー・オールドアダム", "assets/audio/dateless-bar-old-adam/01.mp3"),
      track("燕石博物誌が連れてきた闇", "assets/audio/dateless-bar-old-adam/02.mp3"),
      track("リバースイデオロギー", "assets/audio/dateless-bar-old-adam/03.mp3"),
      track("アウトサイダーカクテル", "assets/audio/dateless-bar-old-adam/04.mp3"),
      track("大神神話伝", "assets/audio/dateless-bar-old-adam/05.mp3"),
      track("パンデモニックプラネット", "assets/audio/dateless-bar-old-adam/06.mp3"),
      track("旧世界の冒険酒場", "assets/audio/dateless-bar-old-adam/07.mp3"),
      track("魔界地方都市エソテリア", "assets/audio/dateless-bar-old-adam/08.mp3"),
      track("亡失のエモーション", "assets/audio/dateless-bar-old-adam/09.mp3"),
      track("二日酔いの同床異夢", "assets/audio/dateless-bar-old-adam/10.mp3"),
    ],
    story: storyPlaceholders([
      ["Old Adam", "オールドアダム"],
      ["燕石带来的黑暗", "燕石が連れてきた闇"],
      ["局外人的鸡尾酒", "アウトサイダーカクテル"],
      ["旧世界的酒馆", "旧世界の酒場"],
      ["同床异梦", "同床異夢"],
    ]),
  },
  {
    id: "taboo-japan-disentanglement",
    catalog: "ZCDS-0024",
    year: "2024",
    color: "rgba(104, 161, 188, 0.24)",
    source: "https://thwiki.cc/%E4%B8%83%E5%A4%95%E5%9D%82%E6%A2%A6%E5%B9%BB%E8%83%BD/%E9%99%84%E5%B8%A6%E6%95%85%E4%BA%8B",
    title: {
      zh: "七夕坂梦幻能",
      ja: "七夕坂夢幻能",
    },
    summary: {
      zh: "最新的秘封音乐 CD 故事，继续把日本民俗、现代观测与禁忌感编织在一起。",
      ja: "秘封音楽 CD の新しい物語。日本民俗、現代の観測、禁忌の感覚がさらに編み込まれます。",
    },
    tracks: [
      track("七夕坂に朝が来る", "assets/audio/taboo-japan-disentanglement/01.mp3"),
      track("不等式のティンカーベル", "assets/audio/taboo-japan-disentanglement/02.mp3"),
      track("禁断の扉の向こうは、この世かあの世か", "assets/audio/taboo-japan-disentanglement/03.mp3"),
      track("スモーキングドラゴン", "assets/audio/taboo-japan-disentanglement/04.mp3"),
      track("夢幻能　～ Taboo Marionette", "assets/audio/taboo-japan-disentanglement/05.mp3"),
      track("クレイジーバックダンサーズ", "assets/audio/taboo-japan-disentanglement/06.mp3"),
      track("憑坐は夢と現の間に　～ Necro-Fantasia", "assets/audio/taboo-japan-disentanglement/07.mp3"),
      track("ひとりぼっちの常陸行路", "assets/audio/taboo-japan-disentanglement/08.mp3"),
      track("地蔵だけが知る哀嘆", "assets/audio/taboo-japan-disentanglement/09.mp3"),
      track("秘匿されたフォーシーズンズ", "assets/audio/taboo-japan-disentanglement/10.mp3"),
    ],
    story: storyPlaceholders([
      ["七夕坂的早晨", "七夕坂の朝"],
      ["不等式与小妖精", "不等式と妖精"],
      ["禁断之门", "禁断の扉"],
      ["梦幻能", "夢幻能"],
      ["梦与现之间", "夢と現の間"],
    ]),
  },
];

function track(title, audio) {
  return { title, audio };
}

function storyPlaceholders(titles) {
  return titles.map(([zhTitle, jaTitle], index) => ({
    track: index + 1,
    title: {
      zh: zhTitle,
      ja: jaTitle,
    },
    text: {
      zh: `【${zhTitle}】这里是已授权简体中文小说正文的占位位置。建议把专辑 Booklet 的段落按曲目氛围拆分到这个章节中；播放器切换到对应曲目时，会自动高亮并滚动到这里。`,
      ja: `【${jaTitle}】ここは許諾済み日本語本文のプレースホルダーです。ブックレット本文を曲の雰囲気に合わせて分割して入れると、再生中の曲に対応して強調表示されます。`,
    },
  }));
}
